# AI-Powered QA with tosijs-dev
# 
# Add this to .github/workflows/ai-qa.yml
# 
# Required secrets:
#   ANTHROPIC_API_KEY - Your Anthropic API key
#
# Usage:
#   1. Copy this file to .github/workflows/ai-qa.yml
#   2. Add ANTHROPIC_API_KEY to repository secrets
#   3. Adjust the "Start application" step for your app

name: AI QA

on:
  pull_request:
    branches: [main]
  workflow_dispatch:  # Manual trigger

jobs:
  ai-qa:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
          
      - name: Install Playwright
        run: npx playwright install chromium
        
      - name: Install dependencies
        run: npm ci
        
      # ================================================
      # CUSTOMIZE THIS STEP FOR YOUR APPLICATION
      # ================================================
      - name: Start application
        run: |
          npm start &
          echo "Waiting for app to start..."
          sleep 10
          curl --retry 5 --retry-delay 2 --retry-connrefused http://localhost:3000 || exit 1
        env:
          NODE_ENV: test
          
      - name: Start tosijs-dev
        run: |
          bunx tosijs-dev &
          sleep 3
          curl --retry 3 --retry-delay 1 http://localhost:8700/status
          
      - name: Run AI QA
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        run: |
          # Run the AI QA prompt
          npx claude -p "$(cat .tosijs/prompts/run-tests.md)" \
            --max-turns 50 \
            --output results.json \
            2>&1 | tee ai-qa.log
            
      - name: Check results
        run: |
          # Extract summary and check for failures
          if [ -f results.json ]; then
            echo "=== AI QA Results ==="
            cat results.json | jq '.'
            
            # Fail if any tests failed
            FAILED=$(cat results.json | jq -r '.summary.failed // 0')
            if [ "$FAILED" -gt 0 ]; then
              echo "::error::$FAILED test(s) failed"
              exit 1
            fi
          else
            echo "::warning::No results.json produced"
            cat ai-qa.log
          fi
          
      - name: Upload results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ai-qa-report
          path: |
            results.json
            ai-qa.log
          retention-days: 30
          
      - name: Comment on PR
        if: failure() && github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            let body = '## AI QA Failed\n\n';
            
            try {
              const results = JSON.parse(fs.readFileSync('results.json', 'utf8'));
              body += `**Summary**: ${results.summary.passed} passed, ${results.summary.failed} failed\n\n`;
              
              if (results.overallAnalysis) {
                body += `**Analysis**: ${results.overallAnalysis}\n\n`;
              }
              
              const failures = results.results.filter(r => !r.passed);
              if (failures.length > 0) {
                body += '### Failures\n\n';
                for (const f of failures) {
                  body += `- **${f.test}**: ${f.error}\n`;
                  if (f.suggestion) {
                    body += `  - 💡 ${f.suggestion}\n`;
                  }
                }
              }
            } catch (e) {
              body += 'Could not parse results. Check the workflow logs.';
            }
            
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: body
            });
