#!/usr/bin/env bun
/**
 * Main build script for Haltija
 * Compiles TypeScript, bundles for browser/bun targets, syncs to desktop app
 */

import { $ } from 'bun'
import { writeFileSync, readFileSync, existsSync } from 'fs'

// 0. Generate version.ts from package.json (single source of truth)
const pkg = JSON.parse(readFileSync('package.json', 'utf-8'))
writeFileSync('src/version.ts', `/**
 * Haltija - Browser Control for AI Agents
 * https://github.com/tonioloewald/haltija
 *
 * Copyright 2025 Tonio Loewald
 * SPDX-License-Identifier: Apache-2.0
 *
 * ⚠️  AUTO-GENERATED FROM package.json - DO NOT EDIT THIS FILE
 * ⚠️  To change the version, update package.json and run: bun run build
 */

export const VERSION = '${pkg.version}'
`)

// 1. Generate schema-derived files BEFORE embedding (they become embedded assets)
const { ALL_ENDPOINTS, getInputSchema } = await import('../src/api-schema')
const mcpEndpoints = ALL_ENDPOINTS
  .filter(ep => (ep as any).visibility !== 'internal')
  .map(ep => ({
    path: ep.path,
    method: ep.method,
    summary: ep.summary,
    description: ep.description,
    inputSchema: getInputSchema(ep),
  }))
writeFileSync('apps/mcp/src/endpoints.json', JSON.stringify(mcpEndpoints, null, 2))

// Generate CLI hints from schema (path -> hint)
const cliHints: Record<string, string> = {}
for (const ep of ALL_ENDPOINTS) {
  if ((ep as any).hints) {
    // Convert path to CLI subcommand name (e.g., /tree -> tree, /events/watch -> events-watch)
    const subcommand = ep.path.slice(1).replace(/\//g, '-')
    cliHints[subcommand] = (ep as any).hints
  }
}
writeFileSync('bin/hints.json', JSON.stringify(cliHints, null, 2))

// 6. Generate API.md from api-schema (single source of truth)
function generateApiMd(): string {
  const lines: string[] = [
    '# Haltija API Reference',
    '',
    '> **Auto-generated from `src/api-schema.ts`** - Do not edit directly.',
    '',
    '## Quick Start',
    '',
    '```bash',
    '# Is it working?',
    'curl localhost:8700/status',
    '',
    '# What tabs are connected?',
    'curl localhost:8700/windows',
    '',
    "# What's on the page?",
    'curl -X POST localhost:8700/tree -d \'{"mode":"actionable"}\'',
    '',
    '# Click something',
    'curl -X POST localhost:8700/click -d \'{"selector":"#submit"}\'',
    '```',
    '',
    '---',
    '',
  ]

  // Group endpoints by category - ordered by "what you need first"
  // Filter out internal endpoints (visibility: 'internal')
  const byCategory = new Map<string, typeof ALL_ENDPOINTS>()
  for (const ep of ALL_ENDPOINTS) {
    // Skip internal endpoints - they're not part of the public API
    if ((ep as any).visibility === 'internal') continue
    
    const cat = (ep as any).category || 'other'
    if (!byCategory.has(cat)) byCategory.set(cat, [])
    byCategory.get(cat)!.push(ep)
  }

  // Order by workflow: connect -> see -> do -> watch -> advanced
  const categoryOrder = ['meta', 'dom', 'interaction', 'navigation', 'events', 'mutations', 'selection', 'windows', 'recording', 'testing', 'debug', 'other']
  const categoryTitles: Record<string, string> = {
    meta: 'Connection & Status',
    dom: 'See the Page',
    interaction: 'Do Things',
    navigation: 'Navigate',
    events: 'Watch What Happens',
    mutations: 'Watch DOM Changes',
    selection: 'User Selection',
    windows: 'Multiple Tabs',
    recording: 'Record & Replay',
    testing: 'Run Tests',
    debug: 'Escape Hatches',
    other: 'Other',
  }

  for (const cat of categoryOrder) {
    const eps = byCategory.get(cat)
    if (!eps || eps.length === 0) continue

    lines.push(`## ${categoryTitles[cat] || cat}`)
    lines.push('')

    for (const ep of eps) {
      lines.push(`### \`${ep.method} ${ep.path}\``)
      lines.push('')
      lines.push(`**${ep.summary}**`)
      lines.push('')
      
      if (ep.description) {
        lines.push(ep.description)
        lines.push('')
      }

      const schema = getInputSchema(ep)
      if (schema && (schema as any).properties) {
        const props = (schema as any).properties
        const propNames = Object.keys(props)
        if (propNames.length > 0) {
          lines.push('**Parameters:**')
          lines.push('')
          lines.push('| Name | Type | Description |')
          lines.push('|------|------|-------------|')
          for (const name of propNames) {
            const prop = props[name]
            const type = prop.type || 'any'
            const desc = prop.description || ''
            const required = (schema as any).required?.includes(name) ? ' *(required)*' : ''
            lines.push(`| \`${name}\` | ${type} | ${desc}${required} |`)
          }
          lines.push('')
        }
      }

      // Add examples if present
      const examples = (ep as any).examples
      if (examples && examples.length > 0) {
        lines.push('**Examples:**')
        lines.push('')
        for (const ex of examples) {
          lines.push(`- **${ex.name}**: ${ex.description || ''}`)
          lines.push('  ```json')
          lines.push(`  ${JSON.stringify(ex.input)}`)
          lines.push('  ```')
          
          // Include response example if present
          if (ex.response) {
            lines.push('  Response:')
            lines.push('  ```json')
            lines.push(`  ${JSON.stringify(ex.response, null, 2).split('\n').join('\n  ')}`)
            lines.push('  ```')
          }
          
          // Include curl example if present
          if (ex.curl) {
            lines.push('  ```bash')
            lines.push(`  ${ex.curl}`)
            lines.push('  ```')
          }
        }
        lines.push('')
      }

      lines.push('---')
      lines.push('')
    }
  }

  return lines.join('\n')
}

writeFileSync('API.md', generateApiMd())

// 7. Generate DOCS.md - hj-centric quick start (single source of truth)
function generateDocsMd(): string {
  const lines: string[] = [
    '# Haltija: Browser Control for AI Agents',
    '',
    '> **Auto-generated from `src/api-schema.ts`** - Do not edit directly.',
    '',
    'You have access to a live browser tab. Use the `hj` command to see the DOM,',
    'click elements, type text, run JavaScript, and watch for changes.',
    '',
    '## Quick Start',
    '',
    '```',
    'hj status              # Check connection',
    'hj tree                # See page structure (ref IDs for targeting)',
    'hj click 42            # Click element by ref ID',
    'hj click "#submit"     # Click by CSS selector',
    'hj type 10 "hello"     # Type into input (realistic keystroke simulation)',
    'hj key Enter           # Press keys',
    'hj screenshot          # Capture page',
    'hj --help              # All commands',
    '```',
    '',
    '## Commands by Category',
    '',
  ]

  // Group endpoints by category
  const byCategory = new Map<string, typeof ALL_ENDPOINTS>()
  for (const ep of ALL_ENDPOINTS) {
    if ((ep as any).visibility === 'internal') continue
    const cat = (ep as any).category || 'other'
    if (!byCategory.has(cat)) byCategory.set(cat, [])
    byCategory.get(cat)!.push(ep)
  }

  const categoryOrder = ['meta', 'dom', 'interaction', 'navigation', 'events', 'mutations', 'selection', 'windows', 'recording', 'testing', 'debug']
  const categoryTitles: Record<string, string> = {
    meta: 'Status & Info',
    dom: 'See the Page',
    interaction: 'Interact',
    navigation: 'Navigate',
    events: 'Watch Events',
    mutations: 'Watch DOM Changes',
    selection: 'User Selection',
    windows: 'Multiple Tabs',
    recording: 'Record & Replay',
    testing: 'Run Tests',
    debug: 'Debug & Eval',
  }

  // Map REST paths to hj subcommands
  const pathToHj = (path: string, method: string): string => {
    // /mutations/watch -> mutations-watch, /test/run -> test-run
    const sub = path.slice(1).replace(/\//g, '-')
    return `hj ${sub}`
  }

  for (const cat of categoryOrder) {
    const eps = byCategory.get(cat)
    if (!eps || eps.length === 0) continue

    lines.push(`### ${categoryTitles[cat] || cat}`)
    lines.push('')

    for (const ep of eps) {
      const hj = pathToHj(ep.path, ep.method)
      const params = getInputSchema(ep)
      const paramKeys = params && (params as any).properties ? Object.keys((params as any).properties) : []
      const paramHint = paramKeys.length > 0 ? ` [${paramKeys.slice(0, 3).join(', ')}${paramKeys.length > 3 ? ', ...' : ''}]` : ''
      lines.push(`- \`${hj}${paramHint}\` - ${ep.summary}`)
    }
    lines.push('')
  }

  lines.push('## Tips')
  lines.push('')
  lines.push('1. `hj tree` first — ref IDs are the fastest way to target elements')
  lines.push('2. Selectors support `:text()` pseudo-selector: `hj click "button:text(Sign in)"`')
  lines.push('3. `:text(/regex/i)` for regex matching: `hj click "a:text(/sign\\s+up/i)"`')
  lines.push('4. `hj events` shows what happened — aggregated semantic events, not raw DOM')
  lines.push('5. `hj highlight 42 "Look here"` to show the user something')
  lines.push('6. `hj recording start` survives page navigations — record OAuth flows, multi-page checkouts')
  lines.push('7. `hj api` for the full API reference with all parameters')
  lines.push('')
  lines.push('## Targeting a Specific Server')
  lines.push('')
  lines.push('Each project should run its own haltija. The friendliest way to address it')
  lines.push('is by name — every `haltija --name <foo>` registers itself in')
  lines.push('`~/.haltija/servers/` and `hj` resolves the name back to a port:')
  lines.push('')
  lines.push('```bash')
  lines.push('haltija --name dashboard --server      # start the server (any free port)')
  lines.push('export HALTIJA_NAME=dashboard           # tell hj which one to talk to')
  lines.push('hj tree')
  lines.push('')
  lines.push('hj --name dashboard tree                # one-off override')
  lines.push('```')
  lines.push('')
  lines.push('Or pin a port directly if you prefer:')
  lines.push('')
  lines.push('```bash')
  lines.push('export HALTIJA_PORT=9123')
  lines.push('hj --port 9123 tree')
  lines.push('```')
  lines.push('')
  lines.push('When the server is started with `--token <secret>`, set `HALTIJA_TOKEN` to')
  lines.push('match (or pass `--token <secret>` to `hj`).')
  lines.push('')
  lines.push('## Embed Haltija in Your App')
  lines.push('')
  lines.push('```js')
  lines.push("import { inject } from 'haltija/component'")
  lines.push("inject('ws://localhost:9123/ws/browser')                    // visible widget")
  lines.push("inject('ws://localhost:9123/ws/browser', { mode: 'headless' })  // invisible")
  lines.push("inject('ws://localhost:9123/ws/browser', { token: 'secret' }) // production")
  lines.push('```')
  lines.push('')
  lines.push('Or in HTML: `<haltija-dev server="ws://localhost:9123/ws/browser"></haltija-dev>`')
  lines.push('')
  lines.push('## Auto-Launch')
  lines.push('')
  lines.push('If no browser windows are connected, `hj` automatically launches the Haltija')
  lines.push('desktop app (macOS). Use `--no-launch` to disable this behavior.')
  lines.push('')
  lines.push('```bash')
  lines.push('hj tree                   # Auto-launches Haltija.app if needed')
  lines.push('hj tree --no-launch       # Skip auto-launch')
  lines.push('hj status                 # Info commands never trigger auto-launch')
  lines.push('```')
  lines.push('')
  lines.push('## CI / Headless')
  lines.push('')
  lines.push('```bash')
  lines.push('# Install deps (Ubuntu)')
  lines.push('apt-get install -y xvfb jq libnss3 libatk1.0-0 libatk-bridge2.0-0 \\')
  lines.push('  libcups2 libdrm2 libxkbcommon0 libxcomposite1 libxdamage1 \\')
  lines.push('  libxfixes3 libxrandr2 libgbm1 libasound2t64')
  lines.push('')
  lines.push('# Start Haltija in CI mode (Electron + xvfb)')
  lines.push('export PATH="$HOME/.local/bin:$PATH"')
  lines.push('xvfb-run --auto-servernum bunx haltija@latest --ci &')
  lines.push('')
  lines.push('# --ci waits for ready, then run tests')
  lines.push('hj test-run tests/my-test.json')
  lines.push('```')
  lines.push('')
  lines.push('See docs/CI-INTEGRATION.md for complete examples.')
  lines.push('')
  lines.push('## Test Runner')
  lines.push('')
  lines.push('```')
  lines.push('hj test-run tests/login.json       # Run a test')
  lines.push('hj test-validate tests/login.json   # Validate format')
  lines.push('hj test-suite tests/a.json tests/b.json  # Run multiple')
  lines.push('```')
  lines.push('')
  lines.push('Test steps: `navigate`, `click`, `type`, `check`, `key`, `select`, `cut`, `copy`, `paste`, `wait`, `assert`, `eval`, `verify`')
  lines.push('')
  lines.push('The `type` action uses realistic per-character keystroke simulation by default.')
  lines.push('Add `"paste": true` for fast paste-style input (still framework-compatible).')
  lines.push('')
  lines.push('## Full API Reference')
  lines.push('')
  lines.push('Run `hj api` for complete endpoint docs with all parameters and examples.')

  return lines.join('\n')
}

writeFileSync('DOCS.md', generateDocsMd())

// 6b. Generate llms.txt - discovery file for AI agents (https://llmstxt.org)
// A concise, link-first overview of the library so an agent encountering Haltija
// (via npm or a live server) can understand its capabilities and find the details.
const REPO_URL = 'https://github.com/tonioloewald/haltija'
const RAW_BASE = `${REPO_URL}/blob/main`

function generateLlmsTxt(): string {
  const lines: string[] = [
    '# Haltija',
    '',
    `> ${pkg.description}`,
    '',
    'Haltija gives AI agents eyes and hands in a real browser. A widget injected into a',
    'browser tab connects over WebSocket to a local server that agents drive via the `hj`',
    'CLI or plain HTTP/REST. Agents see the actual DOM with stable ref IDs, click and type',
    'like a user, run JavaScript, and watch aggregated semantic events — instead of guessing.',
    '',
    '## Documentation',
    `- [Quick start (hj CLI)](${RAW_BASE}/DOCS.md): Agent-facing quick start — the \`hj\` commands and embedding snippet.`,
    `- [REST API reference](${RAW_BASE}/API.md): Every endpoint with parameters and examples (auto-generated from the schema).`,
    `- [README](${RAW_BASE}/README.md): Project overview and setup.`,
    `- [Architecture & contributor guide](${RAW_BASE}/CLAUDE.md): How the server, widget, and CLI fit together.`,
    '',
    '## Capabilities',
  ]

  // Group public endpoints by category, mirroring the DOCS.md ordering.
  const byCategory = new Map<string, typeof ALL_ENDPOINTS>()
  for (const ep of ALL_ENDPOINTS) {
    if ((ep as any).visibility === 'internal') continue
    const cat = (ep as any).category || 'other'
    if (!byCategory.has(cat)) byCategory.set(cat, [])
    byCategory.get(cat)!.push(ep)
  }
  const categoryOrder = ['meta', 'dom', 'interaction', 'navigation', 'events', 'mutations', 'selection', 'windows', 'recording', 'testing', 'debug', 'other']
  const categoryTitles: Record<string, string> = {
    meta: 'Status & info', dom: 'See the page', interaction: 'Interact',
    navigation: 'Navigate', events: 'Watch events', mutations: 'Watch DOM changes',
    selection: 'User selection', windows: 'Multiple tabs', recording: 'Record & replay',
    testing: 'Run tests', debug: 'Debug & eval', other: 'Other',
  }
  for (const cat of categoryOrder) {
    const eps = byCategory.get(cat)
    if (!eps || eps.length === 0) continue
    const summary = eps.map(ep => `\`${ep.method} ${ep.path}\``).join(', ')
    lines.push(`- **${categoryTitles[cat] || cat}**: ${summary}`)
  }
  lines.push('')

  lines.push('## Running Haltija')
  lines.push('')
  lines.push('Two first-party ways to run (plus embedding, below):')
  lines.push('')
  lines.push('- **Local dev & debugging (the paved path):** run a per-project server and drive')
  lines.push('  it with the `hj` CLI or a coding agent (e.g. Claude Code) talking straight to')
  lines.push('  the REST API. `bunx haltija --server --name myproject` starts a server your own')
  lines.push('  browser attaches to via the injected widget; `bunx haltija` launches a bundled')
  lines.push('  browser with the server embedded. Point `hj` at it with `hj --name myproject …`')
  lines.push('  (or `export HALTIJA_NAME=myproject`), and `hj where` to see what a shell targets.')
  lines.push('- **CI:** `haltija --headless` (or `--ci`) runs a headless Chromium with the widget')
  lines.push('  auto-injected — deterministic, no desktop app required. See the CI guide below.')
  lines.push('')
  lines.push('## Embed in your app')
  lines.push('')
  lines.push('```js')
  lines.push("import { inject } from 'haltija/component'  // ESM (bundler)")
  lines.push("inject('ws://localhost:8700/ws/browser')                       // visible widget")
  lines.push("inject('ws://localhost:8700/ws/browser', { mode: 'headless' }) // invisible")
  lines.push('```')
  lines.push('')
  lines.push('Or via a script tag (auto-injecting IIFE bundle served by the running server):')
  lines.push('')
  lines.push('```html')
  lines.push('<script src="http://localhost:8700/component.js?autoInject=true&serverUrl=ws://localhost:8700/ws/browser"></script>')
  lines.push('```')
  lines.push('')

  lines.push('## Optional')
  lines.push(`- [Recipes](${RAW_BASE}/docs/recipes.md): Common workflows (login flows, codebase exploration, recording bug reports).`)
  lines.push(`- [CI integration](${RAW_BASE}/docs/CI-INTEGRATION.md): Running Haltija headless in CI.`)
  lines.push(`- [Agent prompt](${RAW_BASE}/docs/agent-prompt.md): Drop-in instructions for an agent using Haltija.`)
  lines.push('- `GET /llms.txt`, `GET /docs`, `GET /api`, `GET /endpoints`: A running server serves these live for discovery.')
  lines.push('')

  return lines.join('\n')
}

writeFileSync('llms.txt', generateLlmsTxt())

// 3. Build browser component (IIFE for script-tag injection + /component.js).
//    Built BEFORE embed-assets so the IIFE can be embedded into the server bundle,
//    making dist/server.js self-contained (it can always serve /component.js).
await $`bun build ./src/component.ts --outdir=dist --target=browser --format=iife`

// 3b. Build browser component as ESM (real exports) for bundler imports:
//     import { inject, VERSION, DevChannel } from 'haltija/component'
await $`bun build ./src/component.ts --target=browser --format=esm --outfile=dist/component.esm.js`

// 2. Embed static assets into TypeScript (after schema-derived files + component.js exist)
await $`bun run scripts/embed-assets.ts`

// 4. Build server, client, and index for Bun runtime (bundles the embedded component)
await $`bun build ./src/server.ts ./src/client.ts ./src/index.ts ./src/test.ts --outdir=dist --target=bun`

// 4b. Type-check and emit TypeScript declarations (.d.ts) for all entry points —
//     bun build does neither. tsconfig.build.json excludes *.test.ts so only
//     shippable types are emitted. The build is GATED on this: any type error
//     fails the build, so type debt cannot silently re-accumulate. (tsc still
//     emits declarations alongside errors, so the .d.ts are produced regardless.)
{
  const tsc = await $`bunx tsc -p tsconfig.build.json --emitDeclarationOnly`.nothrow().quiet()
  const out = tsc.stdout.toString() + tsc.stderr.toString()
  const errCount = (out.match(/error TS\d+/g) || []).length
  const entryDts = ['index', 'component', 'server', 'client', 'test']
  const missing = entryDts.filter(n => !existsSync(`dist/${n}.d.ts`))
  if (missing.length > 0) {
    throw new Error(`Declaration emit failed for entry points: ${missing.join(', ')}`)
  }
  if (errCount > 0) {
    console.error(out.trim())
    throw new Error(`Type check failed: ${errCount} error(s). Fix them or run \`bunx tsc -p tsconfig.build.json --emitDeclarationOnly\` to see details.`)
  }
}

// 5. Sync component to desktop app resources (single source of truth)
await $`cp dist/component.js apps/desktop/resources/component.js`.quiet().nothrow()

// 5b. Bundle CodeMirror 6 as IIFE for terminal.html file viewer
const cmBuild = await Bun.build({
  entrypoints: ['src/codemirror-bundle.ts'],
  outdir: 'dist',
  naming: 'codemirror-raw.js',
  format: 'esm',
  target: 'browser',
  minify: true,
})
// Wrap as IIFE with global assignment (Bun's globalName doesn't work reliably with IIFE)
if (cmBuild.outputs.length > 0) {
  const cmCode = await cmBuild.outputs[0].text()
  // Convert ESM exports to global assignment
  // The ESM bundle has export { ... } at the end — we capture them as window.CM
  const wrappedCode = `(function(){var _m={};${cmCode.replace(/export\s*\{([^}]+)\}/g, (_, exports) => {
    const assignments = exports.split(',').map((e: string) => {
      const parts = e.trim().split(/\s+as\s+/)
      const local = parts[0].trim()
      const exported = (parts[1] || parts[0]).trim()
      return `_m.${exported}=${local}`
    }).join(';')
    return assignments
  })};window.CM=_m;})()`
  writeFileSync('dist/codemirror.js', wrappedCode)
}
await $`cp dist/codemirror.js apps/desktop/resources/codemirror.js`.quiet().nothrow()

// 6. Bundle hj CLI as standalone file (no relative imports needed)
await $`bun build ./bin/hj.mjs --outfile=dist/hj.js --target=node --format=esm`
// Replace shebang with bun — the extensionless copy at ~/.local/bin/hj needs
// ESM support, and bun handles that natively regardless of file extension.
// (bun build preserves the original #!/usr/bin/env node from hj.mjs)
const hjBundle = readFileSync('dist/hj.js', 'utf-8')
const hjWithShebang = hjBundle.startsWith('#!')
  ? '#!/usr/bin/env bun\n' + hjBundle.slice(hjBundle.indexOf('\n') + 1)
  : '#!/usr/bin/env bun\n' + hjBundle
writeFileSync('dist/hj.js', hjWithShebang)

console.log('Build complete')
