#!/usr/bin/env bun
/**
 * Embed Assets Build Script
 * 
 * This script reads all static assets (markdown docs, SVG icons) and generates
 * a TypeScript file with the content as string constants. This ensures the content
 * is available in compiled binaries where filesystem access doesn't work.
 * 
 * Single Source of Truth:
 * - docs/getting-started/*.md -> embedded in generated file
 * - haltija-icon.svg -> embedded in generated file
 * - docs/UX-CRIMES.md -> embedded in generated file
 * 
 * Run this before the main build: bun run scripts/embed-assets.ts
 */

import { readFileSync, writeFileSync, existsSync } from 'fs'
import { join, dirname } from 'path'
import { fileURLToPath } from 'url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const rootDir = join(__dirname, '..')

// Assets to embed
const assets = {
  // Getting started docs
  'docs/getting-started/app.md': 'APP_MD',
  'docs/getting-started/service.md': 'SERVICE_MD',
  'docs/getting-started/playground.md': 'PLAYGROUND_MD',
  
  // Icon
  'haltija-icon.svg': 'ICON_SVG',
  
  // UX Crimes doc
  'docs/UX-CRIMES.md': 'UX_CRIMES_MD',
  
  // API reference (auto-generated from schema)
  'API.md': 'API_MD',
}

function escapeForTemplate(content: string): string {
  // Escape backticks and ${} for template literal
  return content
    .replace(/\\/g, '\\\\')
    .replace(/`/g, '\\`')
    .replace(/\$\{/g, '\\${')
}

function main() {
  const lines: string[] = [
    '/**',
    ' * AUTO-GENERATED FILE - DO NOT EDIT',
    ' * ',
    ' * Generated by scripts/embed-assets.ts',
    ' * Run "bun run build:assets" to regenerate',
    ' * ',
    ' * This file embeds static assets as string constants so they are',
    ' * available in compiled binaries where filesystem access does not work.',
    ' */',
    '',
  ]

  for (const [filePath, varName] of Object.entries(assets)) {
    const fullPath = join(rootDir, filePath)
    
    if (!existsSync(fullPath)) {
      console.error(`Warning: ${filePath} not found, skipping`)
      continue
    }
    
    const content = readFileSync(fullPath, 'utf-8')
    const escaped = escapeForTemplate(content)
    
    lines.push(`export const ${varName} = \`${escaped}\``)
    lines.push('')
    
    console.log(`Embedded: ${filePath} -> ${varName} (${content.length} bytes)`)
  }

  const outputPath = join(rootDir, 'src/embedded-assets.ts')
  writeFileSync(outputPath, lines.join('\n'))
  
  console.log(`\nGenerated: ${outputPath}`)
}

main()
