/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * 
 * Generated by scripts/embed-assets.ts
 * Run "bun run build:assets" to regenerate
 * 
 * This file embeds static assets as string constants so they are
 * available in compiled binaries where filesystem access does not work.
 */

export const APP_MD = `# Haltija App

You're running Haltija in the desktop app. This gives you a browser with superpowers - the Haltija widget is automatically injected into every page you visit, bypassing security restrictions that would normally block it.

## Quick Start

1. **Navigate to any website** using the address bar above
2. **Look for the widget** in the bottom-right corner (the elf icon)
3. **Connect your AI agent** using the REST API at \`http://localhost:8700\`

## For Your AI Agent

Give your agent this prompt to get started:

\`\`\`prompt
I have Haltija running at http://localhost:8700. You can see and control my browser.

**Check connection:**
curl http://localhost:8700/status

**List all open tabs:**
curl http://localhost:8700/windows

**Get current page info:**
curl http://localhost:8700/location

**See the DOM structure:**
curl -X POST http://localhost:8700/tree -H "Content-Type: application/json" -d '{"selector": "body", "depth": 3}'

**Click an element:**
curl -X POST http://localhost:8700/click -H "Content-Type: application/json" -d '{"selector": "#button-id"}'

**Type text:**
curl -X POST http://localhost:8700/type -H "Content-Type: application/json" -d '{"selector": "input", "text": "hello"}'

**Run JavaScript:**
curl -X POST http://localhost:8700/eval -H "Content-Type: application/json" -d '{"code": "document.title"}'

**Open a new tab:**
curl -X POST http://localhost:8700/tabs/open -H "Content-Type: application/json" -d '{"url": "https://example.com"}'

**Target a specific tab:** Add ?window=<id> to any endpoint (get IDs from /windows)

All POST endpoints return: {"success": true, "data": ...} or {"success": false, "error": "..."}

Start with /status to confirm we're connected, then /windows to see open tabs.
\`\`\`

## Useful Commands

Check if the server is running:
\`\`\`bash
curl http://localhost:8700/status
\`\`\`

Get the page structure:
\`\`\`bash
curl -X POST http://localhost:8700/tree -H "Content-Type: application/json" -d '{"selector": "body", "depth": 3}'
\`\`\`

Click a button:
\`\`\`bash
curl -X POST http://localhost:8700/click -H "Content-Type: application/json" -d '{"selector": "button"}'
\`\`\`

## Keyboard Shortcuts

- **Cmd+T** - New tab
- **Cmd+W** - Close tab
- **Cmd+1-9** - Switch to tab
- **Cmd+L** - Focus address bar
- **Cmd+R** - Refresh page
`

export const SERVICE_MD = `# Haltija Service

You're running the Haltija server. To give your AI agent browser control, you need to inject the widget into a web page using the bookmarklet.

## Quick Start

1. **Drag the bookmarklet** below to your bookmarks bar
2. **Open any website** in your browser
3. **Click the bookmarklet** to inject the Haltija widget
4. **Connect your AI agent** using the REST API at \`http://localhost:8700\`

## The Bookmarklet

Drag this to your bookmarks bar:

\`\`\`bookmarklet
Haltija
\`\`\`

Or copy this JavaScript URL and create a bookmark manually:

\`\`\`js
javascript:(function(){var s=document.createElement('script');s.src='http://localhost:8700/inject.js';document.body.appendChild(s);})()
\`\`\`

## For Your AI Agent

Give your agent this prompt to get started:

\`\`\`prompt
I have Haltija running at http://localhost:8700. You can see and control my browser.

**Quick start:**
1. Check server: curl http://localhost:8700/status
2. Find tabs: curl http://localhost:8700/windows
3. See what's on page: curl -X POST http://localhost:8700/tree -d '{"selector":"body","mode":"actionable"}'
4. Do something: curl -X POST http://localhost:8700/click -d '{"selector":"button"}'

**Key endpoints:**
- GET /windows - list connected tabs
- GET /location?window=ID - current URL
- POST /tree - see page structure (use mode:"actionable" for summary of buttons/links/inputs)
- POST /click - click an element
- POST /type - type into a field
- POST /eval - run JavaScript (escape hatch)
- POST /screenshot - capture page image (see options below)
- GET /events - recent events including network errors

**Screenshot options:**
- format: "png" (default), "webp", "jpeg"
- quality: 0.0-1.0 (for webp/jpeg, default 0.8)
- scale: 0.5 = half size (saves bandwidth)
- maxWidth/maxHeight: constrain dimensions (great for vision models)

**Tree options:**
- mode:"actionable" - returns buttons, links, inputs, headings (recommended)
- visibleOnly:true - filter out hidden elements
- depth:3 - how deep to traverse

**Target a specific tab:** Add ?window=<id> or include "window":"id" in POST body

All POST endpoints return: {"success": true, "data": ...} or {"success": false, "error": "..."}
\`\`\`

For the full agent prompt with more examples, see [agent-prompt.md](../agent-prompt.md).

## Useful Commands

Start the server (if not already running):
\`\`\`bash
bunx haltija
\`\`\`

Check server status:
\`\`\`bash
curl http://localhost:8700/status
\`\`\`

Get the page structure:
\`\`\`bash
curl -X POST http://localhost:8700/tree -H "Content-Type: application/json" -d '{"selector": "body", "depth": 3}'
\`\`\`

## Troubleshooting

**Widget not appearing?**
- Some sites have strict CSP that blocks the widget
- Try the Haltija desktop app for universal compatibility

**Agent can't connect?**
- Make sure you clicked the bookmarklet after the page loaded
- Check that the widget shows a green status ring (connected)
`

export const PLAYGROUND_MD = `# Playground

This is a sandbox for testing Haltija commands. The elements below are designed for agents to practice interacting with web pages.

## Interactive Elements

Use these to test clicking, typing, and reading page content.

### Buttons

<div class="test-buttons">
  <button id="btn-primary" class="btn-test primary">Primary Button</button>
  <button id="btn-secondary" class="btn-test secondary">Secondary Button</button>
  <button id="btn-danger" class="btn-test danger">Danger Button</button>
</div>

### Form Inputs

<div class="test-form">
  <div class="form-row">
    <label for="text-input">Text Input:</label>
    <input type="text" id="text-input" placeholder="Type something here...">
  </div>
  <div class="form-row">
    <label for="email-input">Email:</label>
    <input type="email" id="email-input" placeholder="you@example.com">
  </div>
  <div class="form-row">
    <label for="select-input">Dropdown:</label>
    <select id="select-input">
      <option value="">Choose an option...</option>
      <option value="a">Option A</option>
      <option value="b">Option B</option>
      <option value="c">Option C</option>
    </select>
  </div>
  <div class="form-row">
    <label>Checkboxes:</label>
    <div class="checkbox-group">
      <label><input type="checkbox" id="check-1"> Option 1</label>
      <label><input type="checkbox" id="check-2"> Option 2</label>
      <label><input type="checkbox" id="check-3"> Option 3</label>
    </div>
  </div>
</div>

### Output Area

<div id="output" class="output-box">
  Click buttons or type in fields to see results here.
</div>

## Test Commands

Try these commands to interact with the playground:

Click the primary button:
\`\`\`bash
curl -X POST http://localhost:8700/click -H "Content-Type: application/json" -d '{"selector": "#btn-primary"}'
\`\`\`

Type in the text input:
\`\`\`bash
curl -X POST http://localhost:8700/type -H "Content-Type: application/json" -d '{"selector": "#text-input", "text": "Hello from the agent!"}'
\`\`\`

Read the output area:
\`\`\`bash
curl -X POST http://localhost:8700/query -H "Content-Type: application/json" -d '{"selector": "#output"}'
\`\`\`

Get all form values:
\`\`\`bash
curl -X POST http://localhost:8700/eval -H "Content-Type: application/json" -d '{"code": "JSON.stringify({text: document.getElementById(\\"text-input\\").value, email: document.getElementById(\\"email-input\\").value})"}'
\`\`\`
`

export const ICON_SVG = `<?xml version="1.0" encoding="utf-8"?>
<svg x="0px" y="0px" width="1024px" height="1024px" viewBox="0 0 1024 1024" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
  <!--Generated by AMDN-->
  <g id="Layer_1">
    <radialGradient cx="512" cy="512" r="512" fx="512" fy="512" gradientUnits="userSpaceOnUse" gradientTransform="matrix(1,0,0,1,0,0)" id="am2">
      <stop style="stop-color:#3da8f4;stop-opacity:1;"/>
      <stop offset="1" style="stop-color:#382f93;stop-opacity:1;"/>
    </radialGradient>
    <g id="Path">
      <path style="fill:url(#am2);fill-opacity:1;fill-rule:evenodd;opacity:1;stroke:none;" d="M0,128 C0,57.3076,57.3076,1.33227e-15,128,1.33227e-15 C128,1.33227e-15,896,1.33227e-15,896,1.33227e-15 C966.692,1.33227e-15,1024,57.3075,1024,128 C1024,128,1024,896,1024,896 C1024,966.692,966.692,1024,896,1024 C896,1024,128,1024,128,1024 C57.3076,1024,0,966.692,0,896 C0,896,0,128,0,128 z"/>
    </g>
    <path id="Fills" style="fill:#bcffab;fill-opacity:0.2;fill-rule:evenodd;opacity:1;stroke:none;" d="M531,372 C561.928,372,587,397.072,587,428 C587,458.928,561.928,484,531,484 C500.072,484,475,458.928,475,428 C475,397.072,500.072,372,531,372 z"/>
    <path id="Path-1" style="fill:#f4d0ff;fill-opacity:0.4;fill-rule:nonzero;opacity:1;stroke:none;" d="M206,533 C206,533,216,557,216,557 C216,557,211,564,211,564 C211,564,219.463,584.225,219.463,584.225 C219.463,584.225,246.781,589.813,251,605 C256,623,240.373,634.197,242.831,640.071 C249.623,656.303,270,705,270,705 C270,705,302,694,302,694 C302,694,243,549,243,549 C243,549,231,549,231,549 C231,549,221,524,221,524 C221,524,206,533,206,533 z"/>
    <path id="Path-2" style="fill:#f4d0ff;fill-opacity:0.4;fill-rule:nonzero;opacity:1;stroke:none;" d="M924,522"/>
    <path id="Path-3" style="fill:#f4d0ff;fill-opacity:0.4;fill-rule:nonzero;opacity:1;stroke:none;" d="M378,798 C409,804,433,799,434,787 C435,775,451,745,451,745 C451,745,447,729,447,729 C447,729,472,731,472,731 C472,731,471,778,471,778 C471,778,487,812,520,808 C553,804,569,793,570,783 C571,773,572,734,572,734 C572,734,562,660,562,660 C562,660,554,656,554,656 C554,656,559,620,559,620 C559,620,549,606,533,607 C517,608,505,620,505,620 C505,620,506,653,506,653 C506,653,492,662,492,662 C492,662,491,674,491,674 C491,674,482,664,470,662 C458,660,451,663,451,663 C451,663,465,627,465,627 C465,627,458,611,446,608 C434,605,413,611,413,611 C413,611,405,634,405,634 C405,634,409,643,409,643 C409,643,393,648,393,648 C393,648,356,710,356,710 C356,710,338,754,338,754 C338,754,347,792,378,798 z"/>
    <path id="Path-4" style="fill:#bcffab;fill-opacity:0.2;fill-rule:nonzero;opacity:1;stroke:none;" d="M357,740 C357,740,361,765,384,772 C407,779,432,765,432,765 C432,765,424,749,402,743 C380,737,357,740,357,740 z"/>
    <path id="Path_Copy" style="fill:#bcffab;fill-opacity:0.2;fill-rule:nonzero;opacity:1;stroke:none;" d="M483.423,757.649 C483.423,757.649,492.38,781.33,516.319,783.55 C540.257,785.771,561.922,767.019,561.922,767.019 C561.922,767.019,550.862,752.96,528.104,751.517 C505.346,750.075,483.423,757.649,483.423,757.649 z"/>
    <path id="Fills_Copy" style="fill:#bcffab;fill-opacity:0.2;fill-rule:evenodd;opacity:1;stroke:none;" d="M367,373 C397.928,373,423,398.072,423,429 C423,459.928,397.928,485,367,485 C336.072,485,311,459.928,311,429 C311,398.072,336.072,373,367,373 z"/>
    <g id="Group">
      <path id="Path_579" style="fill:#bcffab;fill-opacity:0.2;fill-rule:evenodd;opacity:1;stroke:none;" d="M164,344 C209.287,344,246,380.713,246,426 C246,471.287,209.287,508,164,508 C118.713,508,82,471.287,82,426 C82,380.713,118.713,344,164,344 z"/>
      <path id="Path_578" style="fill:#f4d0ff;fill-opacity:0.4;fill-rule:evenodd;opacity:1;stroke:none;" d="M164,314 C225.856,314,276,364.144,276,426 C276,487.856,225.856,538,164,538 C102.144,538,52,487.856,52,426 C52,364.144,102.144,314,164,314 z M164,344 C209.287,344,246,380.713,246,426 C246,471.287,209.287,508,164,508 C118.713,508,82,471.287,82,426 C82,380.713,118.713,344,164,344 z"/>
      <path id="Path-5" style="fill:#f4d0ff;fill-opacity:0.4;fill-rule:nonzero;opacity:1;stroke:none;" d="M708,315"/>
      <path id="Path-6" style="fill:#b0ff85;fill-opacity:0.4;fill-rule:nonzero;opacity:1;stroke:none;" d="M303,303 C305,311,409.129,323.046,439,326 C530,335,613,309,613,309 C613,309,731,369,731,369 C731,369,738,438,738,438 C738,438,775,445,775,445 C775,445,798,437,799,423 C800,409,754,380,750,358 C746,336,762,161,584,136 C406,111,388,222,386,230 C384,238,374,264,374,264 C374,264,341,272,327,280 C313,288,301,295,303,303 z"/>
    </g>
    <path id="Path-7" style="fill:#b7cdff;fill-opacity:0.15;fill-rule:nonzero;opacity:1;stroke:none;" d="M197,636 C209,659,255,674,255,674 C255,674,243,640,243,640 C243,640,259,621,249,601 C239,581,212,582,204,588 C196,594,185,613,197,636 z"/>
    <path id="Path-8" style="fill:#b7cdff;fill-opacity:0.15;fill-rule:nonzero;opacity:1;stroke:none;" d="M359,322 C359,322,344,370,344,370 C344,370,350,378,350,378 C350,378,341,483,341,483 C341,483,335,499,335,499 C335,499,337,551,337,551 C337,551,261,593,261,593 C261,593,298,681,298,681 C298,681,362,671,362,671 C362,671,369,684,369,684 C369,684,390,650,390,650 C390,650,406,644,406,644 C406,644,402,636,402,636 C402,636,414,610,414,610 C414,610,444,608,444,608 C444,608,464,626,464,626 C464,626,454,662,454,662 C454,662,491,672,491,672 C491,672,506,652,506,652 C506,652,504,642,504,642 C504,642,506,618,506,618 C506,618,529,609,529,609 C529,609,561,623,561,623 C561,623,553,657,553,657 C553,657,564,668,564,668 C564,668,573,743,573,743 C573,743,571,785,571,785 C571,785,554,815,515,808 C476,801,469,775,469,775 C469,775,468,732,468,732 C468,732,444,733,444,733 C444,733,445,748,445,748 C445,748,435,789,435,789 C435,789,499.299,871.287,593,883 C705,897,771,845,820,848 C869,851,933,933,933,933 C933,933,940,837,904,806 C868,775,781,751,767,728 C753,705,751,689,751,689 C751,689,840.933,724.15,857,688 C881,634,763,581,752,541 C741,501,731,365,731,365 C731,365,612,308,612,308 C612,308,534.096,329.723,490,329 C429,328,359,322,359,322 z"/>
    <g id="Outlines">
      <radialGradient cx="142" cy="-84" r="0" fx="142" fy="-84" gradientUnits="userSpaceOnUse" gradientTransform="matrix(1,0,0,1,0,0)" id="am4">
        <stop style="stop-color:#2a5ca5;stop-opacity:1;"/>
        <stop offset="1" style="stop-color:#1b2851;stop-opacity:1;"/>
      </radialGradient>
      <g id="Path-9">
        <path style="fill:url(#am4);fill-opacity:1;fill-rule:nonzero;opacity:1;stroke:none;" d="M142,-84"/>
      </g>
      <path id="Path-10" style="fill:none;opacity:1;stroke:#ffffff;stroke-linecap:butt;stroke-linejoin:miter;stroke-miterlimit:10;stroke-opacity:1;stroke-width:12;" d="M530,370 C562.032,370,588,395.967,588,428 C588,460.033,562.032,486,530,486 C497.967,486,472,460.033,472,428 C472,395.967,497.967,370,530,370 z"/>
      <path id="Path_Copy-1" style="fill:none;opacity:1;stroke:#ffffff;stroke-linecap:butt;stroke-linejoin:miter;stroke-miterlimit:10;stroke-opacity:1;stroke-width:12;" d="M365.998,370 C398.031,370,423.998,395.967,423.998,428 C423.998,460.033,398.031,486,365.998,486 C333.966,486,307.998,460.033,307.998,428 C307.998,395.967,333.966,370,365.998,370 z"/>
      <g id="Group-1">
        <path id="Path_564" style="fill:none;opacity:1;stroke:#ffffff;stroke-linecap:butt;stroke-linejoin:miter;stroke-miterlimit:10;stroke-opacity:1;stroke-width:12;" d="M423.65,421.61 C430.915,416.752,439.202,414,448,414 C456.797,414,465.084,416.752,472.348,421.609"/>
      </g>
      <path id="Path-11" style="fill:#ffffff;fill-opacity:1;fill-rule:evenodd;opacity:1;stroke:none;" d="M517,409 C524.18,409,530,417.954,530,429 C530,440.046,524.18,449,517,449 C509.82,449,504,440.046,504,429 C504,417.954,509.82,409,517,409 z"/>
      <path id="Path_Copy-2" style="fill:#ffffff;fill-opacity:1;fill-rule:evenodd;opacity:1;stroke:none;" d="M369,409 C376.18,409,382,417.954,382,429 C382,440.046,376.18,449,369,449 C361.82,449,356,440.046,356,429 C356,417.954,361.82,409,369,409 z"/>
      <path id="Path-12" style="fill:none;opacity:1;stroke:#ffffff;stroke-linecap:round;stroke-linejoin:round;stroke-miterlimit:10;stroke-opacity:1;stroke-width:12;" d="M486.18,505.843 C483.217,508.291,479.92,510.43,476.313,512.189 C464.028,518.181,450.476,518.626,438.498,514.502"/>
      <g id="Group-2">
        <path id="Path-13" style="fill:none;opacity:1;stroke:#ffffff;stroke-linecap:round;stroke-linejoin:round;stroke-miterlimit:10;stroke-opacity:1;stroke-width:12;" d="M522.176,748.092 C549.973,750.375,571.425,765.389,570.092,781.627 C568.758,797.864,545.143,809.177,517.347,806.894 C489.55,804.611,468.097,789.597,469.431,773.36 C470.764,757.122,494.379,745.809,522.176,748.092 z"/>
        <path id="Path_Copy-3" style="fill:none;opacity:1;stroke:#ffffff;stroke-linecap:round;stroke-linejoin:round;stroke-miterlimit:10;stroke-opacity:1;stroke-width:12;" d="M561.114,764.267 C553.901,776.621,537.556,784.473,519.291,782.973 C500.588,781.437,485.471,770.556,480.73,756.729"/>
        <path id="Path_572" style="fill:none;opacity:1;stroke:#ffffff;stroke-linecap:round;stroke-linejoin:round;stroke-miterlimit:10;stroke-opacity:1;stroke-width:12;" d="M572.957,746.742 C574.29,730.504,552.837,715.49,525.041,713.207 C497.244,710.925,473.629,722.237,472.296,738.475 C472.296,738.475,493.711,665.989,493.711,665.989 C494.637,654.706,511.046,646.845,530.36,648.432 C549.675,650.018,564.581,660.45,563.655,671.733 C563.655,671.733,572.957,746.742,572.957,746.742 z"/>
        <path id="Path_570" style="fill:none;opacity:1;stroke:#ffffff;stroke-linecap:round;stroke-linejoin:round;stroke-miterlimit:10;stroke-opacity:1;stroke-width:12;" d="M557.105,649.02 C557.81,640.434,546.467,632.495,531.768,631.288 C517.07,630.081,504.583,636.062,503.878,644.649 C503.878,644.649,505.763,621.695,505.763,621.695 C506.468,613.109,518.955,607.127,533.653,608.334 C548.352,609.541,559.695,617.48,558.99,626.066 C558.99,626.066,557.105,649.02,557.105,649.02 z"/>
        <path id="Path_574" style="fill:none;opacity:1;stroke:#ffffff;stroke-linecap:round;stroke-linejoin:round;stroke-miterlimit:10;stroke-opacity:1;stroke-width:12;" d="M572.957,746.742 C574.29,730.504,552.837,715.49,525.041,713.207 C497.244,710.925,473.629,722.237,472.296,738.475 C472.296,738.475,469.431,773.36,469.431,773.36 C470.764,757.122,494.379,745.809,522.176,748.092 C549.973,750.375,571.425,765.389,570.092,781.627 C570.092,781.627,572.957,746.742,572.957,746.742 z"/>
      </g>
      <g id="Group-3">
        <path id="Path-14" style="fill:none;opacity:1;stroke:#ffffff;stroke-linecap:round;stroke-linejoin:round;stroke-miterlimit:10;stroke-opacity:1;stroke-width:12;" d="M459.602,707.811 C470.805,710.813,478.496,718.436,476.78,724.838 C475.065,731.239,464.593,733.995,453.39,730.994 C442.187,727.992,434.496,720.369,436.212,713.967 C437.927,707.566,448.399,704.81,459.602,707.811 z"/>
        <path id="Path_Copy-4" style="fill:none;opacity:1;stroke:#ffffff;stroke-linecap:round;stroke-linejoin:round;stroke-miterlimit:10;stroke-opacity:1;stroke-width:12;" d="M436.212,713.967 C436.212,713.967,446.659,674.976,448.375,668.574 C450.09,662.172,460.562,659.416,471.765,662.418 C482.968,665.42,490.659,673.043,488.943,679.444 C487.228,685.846,477.03,723.906,477.03,723.906"/>
      </g>
      <g id="Group_Copy">
        <path id="Path-15" style="fill:none;opacity:1;stroke:#ffffff;stroke-linecap:round;stroke-linejoin:round;stroke-miterlimit:10;stroke-opacity:1;stroke-width:12;" d="M397.349,739.906 C423.704,749.033,440.747,768.911,435.416,784.307 C430.084,799.702,404.398,804.785,378.043,795.658 C351.688,786.532,334.645,766.653,339.976,751.257 C345.307,735.862,370.994,730.78,397.349,739.906 z"/>
        <path id="Path_Copy-5" style="fill:none;opacity:1;stroke:#ffffff;stroke-linecap:round;stroke-linejoin:round;stroke-miterlimit:10;stroke-opacity:1;stroke-width:12;" d="M431.039,765.259 C420.98,775.431,403.195,778.97,385.877,772.973 C368.144,766.832,356.21,752.532,355.058,737.961"/>
        <path id="Path_572-1" style="fill:none;opacity:1;stroke:#ffffff;stroke-linecap:round;stroke-linejoin:round;stroke-miterlimit:10;stroke-opacity:1;stroke-width:12;" d="M446.869,751.232 C452.2,735.836,435.157,715.958,408.802,706.831 C382.448,697.705,356.761,702.787,351.43,718.182 C351.43,718.182,390.204,653.303,390.204,653.303 C393.909,642.605,411.757,639.074,430.07,645.415 C441.186,649.265,449.918,655.867,454.236,662.854"/>
        <path id="Path_570-1" style="fill:none;opacity:1;stroke:#ffffff;stroke-linecap:round;stroke-linejoin:round;stroke-miterlimit:10;stroke-opacity:1;stroke-width:12;" d="M455.827,652.639 C458.646,644.498,449.634,633.987,435.699,629.161 C421.763,624.335,408.18,627.022,405.361,635.163 C405.361,635.163,412.898,613.4,412.898,613.4 C415.717,605.259,429.299,602.572,443.235,607.398 C457.171,612.224,466.183,622.735,463.364,630.876 C463.364,630.876,455.827,652.639,455.827,652.639 z"/>
        <path id="Path_574-1" style="fill:none;opacity:1;stroke:#ffffff;stroke-linecap:round;stroke-linejoin:round;stroke-miterlimit:10;stroke-opacity:1;stroke-width:12;" d="M446.869,751.232 C452.2,735.836,435.157,715.958,408.802,706.831 C382.448,697.705,356.761,702.787,351.43,718.182 C351.43,718.182,339.976,751.257,339.976,751.257 C345.307,735.862,370.994,730.78,397.349,739.906 C423.704,749.033,440.747,768.911,435.416,784.307 C435.416,784.307,446.869,751.232,446.869,751.232 z"/>
      </g>
      <path id="Path-16" style="fill:none;opacity:1;stroke:#ffffff;stroke-linecap:round;stroke-linejoin:round;stroke-miterlimit:10;stroke-opacity:1;stroke-width:12;" d="M589,424 C589,424,666.838,424,680.838,424 C694.838,424,702,439.929,702,447"/>
      <path id="Path-17" style="fill:none;opacity:1;stroke:#ffffff;stroke-linecap:round;stroke-linejoin:round;stroke-miterlimit:10;stroke-opacity:1;stroke-width:12;" d="M165,313 C226.856,313,277,363.144,277,425 C277,486.856,226.856,537,165,537 C103.144,537,53,486.856,53,425 C53,363.144,103.144,313,165,313 z"/>
      <path id="Path_Copy-6" style="fill:none;opacity:1;stroke:#ffffff;stroke-linecap:round;stroke-linejoin:round;stroke-miterlimit:10;stroke-opacity:1;stroke-width:12;" d="M165,342.003 C210.838,342.003,247.997,379.162,247.997,425 C247.997,470.838,210.838,507.997,165,507.997 C119.162,507.997,82.0027,470.838,82.0027,425 C82.0027,379.162,119.162,342.003,165,342.003 z"/>
      <path id="Path_Copy-7" style="fill:none;opacity:1;stroke:#ffffff;stroke-linecap:round;stroke-linejoin:round;stroke-miterlimit:10;stroke-opacity:1;stroke-width:12;" d="M109,425 C109,394.072,134.072,369,165,369"/>
      <g id="Group-4">
        <path id="Rectangle" style="fill:none;opacity:1;stroke:#ffffff;stroke-linecap:round;stroke-linejoin:round;stroke-miterlimit:10;stroke-opacity:1;stroke-width:12;" d="M216.849,583.064 C216.849,583.064,211.143,569.623,211.143,569.623 C208.553,563.522,211.4,556.477,217.5,553.888 C217.5,553.888,229.467,548.808,229.467,548.808 C235.567,546.219,242.612,549.065,245.202,555.166 C245.202,555.166,300.11,684.521,300.11,684.521 C302.699,690.622,299.853,697.667,293.753,700.256 C293.753,700.256,281.786,705.336,281.786,705.336 C275.685,707.925,268.641,705.079,266.051,698.978 C266.051,698.978,256.252,675.893,256.252,675.893"/>
        <path id="Path-18" style="fill:none;opacity:1;stroke:#ffffff;stroke-linecap:round;stroke-linejoin:round;stroke-miterlimit:10;stroke-opacity:1;stroke-width:12;" d="M373,262 C389,204,427.979,130,521,130 C614.021,130,747.501,158.336,747.501,348.983 C747.501,361.73,753,369,791,410"/>
        <path id="Path-19" style="fill:none;opacity:1;stroke:#ffffff;stroke-linecap:round;stroke-linejoin:round;stroke-miterlimit:10;stroke-opacity:1;stroke-width:12;" d="M617,310 C617,310,638,263,630,214 C622,165,579,133,579,133 C579,133,558.206,56.8008,528,86 C498,115,578,133,578,133"/>
        <path id="Path-20" style="fill:none;opacity:1;stroke:#ffffff;stroke-linecap:round;stroke-linejoin:round;stroke-miterlimit:10;stroke-opacity:1;stroke-width:12;" d="M448,264 C448,264,453,198,500,165 C547,132,580,134,580,134 C580,134,636,68,653,108 C670,148,586,136,586,136"/>
        <path id="Path-21" style="fill:none;opacity:1;stroke:#ffffff;stroke-linecap:round;stroke-linejoin:round;stroke-miterlimit:10;stroke-opacity:1;stroke-width:12;" d="M1068,544"/>
        <path id="Path-22" style="fill:none;opacity:1;stroke:#ffffff;stroke-linecap:round;stroke-linejoin:round;stroke-miterlimit:10;stroke-opacity:1;stroke-width:12;" d="M214.739,555.06 C214.739,555.06,204.189,530.206,204.189,530.206 M220.758,523.173 C220.758,523.173,231.308,548.027,231.308,548.027"/>
      </g>
      <path id="Path-23" style="fill:none;opacity:1;stroke:#ffffff;stroke-linecap:round;stroke-linejoin:round;stroke-miterlimit:10;stroke-opacity:1;stroke-width:12;" d="M360,319 C354.203,335.233,349.152,351.914,345.137,373.026 M335.572,477.988 C335.195,491.712,335,506.653,335,523 C335,577.826,347.839,634.968,370.651,687.153 M433.988,789.01 C482.662,845.491,546.116,883,617.045,883 C758.049,883,733.657,850,827,850 C881.083,850,934,933,934,933 C934,933,951,830,880,785 C809,740,765,750,748,689"/>
      <path id="Path-24" style="fill:none;opacity:1;stroke:#ffffff;stroke-linecap:round;stroke-linejoin:round;stroke-miterlimit:10;stroke-opacity:1;stroke-width:12;" d="M356,370 C356,370,345,396,342,427 C339.109,456.877,342,481,342,481"/>
      <path id="Path-25" style="fill:none;opacity:1;stroke:#ffffff;stroke-linecap:round;stroke-linejoin:round;stroke-miterlimit:10;stroke-opacity:1;stroke-width:12;" d="M729,366 C737,402,740,427,742,502 C744,577,861,633.946,861,671 C861,700.069,838,704,816,704 C785.933,704,701,672,679,640"/>
      <path id="Path-26" style="fill:none;opacity:1;stroke:#ffffff;stroke-linecap:round;stroke-linejoin:round;stroke-miterlimit:10;stroke-opacity:1;stroke-width:12;" d="M756,498 C711,513,619,573,564,672"/>
      <path id="Path-27" style="fill:none;opacity:1;stroke:#ffffff;stroke-linecap:round;stroke-linejoin:round;stroke-miterlimit:10;stroke-opacity:1;stroke-width:12;" d="M334,549"/>
      <path id="Path_577" style="fill:none;opacity:1;stroke:#ffffff;stroke-linecap:round;stroke-linejoin:round;stroke-miterlimit:10;stroke-opacity:1;stroke-width:12;" d="M363,669 C363,669,356,676,321,678 C314.561,678.368,307.259,678.465,298,678 M256,675 C225.5,667.673,196,649.737,196,621 C196,613.138,191,584,218,585 C245,586,249,598,251,610 C253,622,251,633,242,640 C253.986,672.057,242,640,242,640 C242,640,256,675,256,675 z"/>
      <path id="Path-28" style="fill:none;opacity:1;stroke:#ffffff;stroke-linecap:round;stroke-linejoin:round;stroke-miterlimit:10;stroke-opacity:1;stroke-width:12;" d="M334,550 C319.284,568.854,288.92,581.342,260.411,591.19"/>
      <path id="Path-29" style="fill:none;opacity:1;stroke:#ffffff;stroke-linecap:round;stroke-linejoin:round;stroke-miterlimit:10;stroke-opacity:1;stroke-width:12;" d="M741,437 C771,450,798.511,446.045,798.511,421.59 C798.511,406.924,716.138,349.664,615.644,309.899 C547.413,282.9,470.829,262,406,262 C353.914,262,302,286,302,301 C302,316,428.469,328,491,328 C553.531,328,610,312,610,312"/>
    </g>
  </g>
</svg>
`

export const UX_CRIMES_MD = `# The Haltija Criminal Code (v1.0)

A comprehensive database of UX anti-patterns that Haltija can detect programmatically.
This turns the agent into a **"Compliance Officer"** and **"Linting Tool for Psychology"**.

> "Make your web app feel like a native app."

---

## Class 1: Interaction Integrity (The "UX Historian" Crimes)

*Violations of 40 years of established OS/GUI conventions. These happen when designers reinvent standard controls in a vacuum.*

### 1. The Conflated Tree View

**The Crime:** Clicking a parent node selects it *and* expands it simultaneously, or selection is impossible without expansion.

**The OS Standard:** Selection (Click) and Expansion (Triangle/Arrow) are distinct actions.

**Haltija Signature:**
- Click parent row
- Check if \`aria-expanded\` toggles *and* \`aria-selected\` toggles instantly
- Verify Arrow Keys (\`Right\` to expand, \`Left\` to collapse) function correctly

---

### 2. The Disclosure Heresy

**The Crime:** An arrow pointing **UP** to indicate an open/expanded state (because "the drawer pulls up"), violating the reading flow convention.

**The OS Standard:** 
- **Right (▶)** = Closed/Next ("content is this way")
- **Down (▼)** = Open ("content flows below")

**The Philosophy:** Designers in a vacuum think "the drawer pulls up, so arrow points up." But users are in **Reading Mode** (following flow), not **Mechanical Mode** (operating a lever).

**Haltija Signature:**
- Compare icon rotation/SVG path between \`aria-expanded="true"\` and \`false\`
- Detect 180° rotation (Down → Up) on inline items
- *Exception:* Bottom-of-screen drawers may legitimately use Up

---

### 3. The Ambiguous Toggle

**The Crime:** A switch that relies solely on color (Green/Grey) or position (Left/Right) without text labels like "On/Off".

**The Issue:** Does "Green" mean it *is* on, or that clicking it *turns* it on? (State vs. Action confusion)

**Haltija Signature:**
- Detect \`role="switch"\` or checkbox styled as toggle
- Check for adjacent \`<label>\` or internal text
- If text is missing → **Crime**

---

### 4. The Scrollbar Lie (Gaslighting Scroll)

**The Crime:** Virtual scrolling that jumps, changes the scrollbar thumb size while dragging, or loses position when scrolling up.

**The OS Standard:** Scrollbars act as a fixed map of the content. 10% scroll movement = 10% content movement.

**Haltija Signature:**
- Measure \`scrollHeight\` change during scroll events
- If \`scrollHeight\` varies by >10% without explicit "Load More" action → **Crime**
- Monitor scroll-up: if \`scrollTop\` jumps by >100px without user input → **Crime**

---

### 5. Multi-Select Amnesia

**The Crime:** A list that requires individual clicking of 50 items because \`Shift+Click\` (Range) and \`Cmd/Ctrl+Click\` (Toggle) are ignored.

**Haltija Signature:**
- Click Item 1
- Hold Shift, Click Item 5
- Check selection count
- If < 5 → **Crime**

---

### 6. Infinite Scroll in Data Tables

**The Crime:** Using infinite scroll in enterprise data grids because "pagination is old school."

**The Reality:** In data grids, position matters. Users need to know "I am roughly 50% through the alphabet." Infinite scroll destroys the scrollbar's utility as a "Map."

**Haltija Signature:**
- Detect a \`<table>\` or \`role="grid"\`
- Scroll to bottom - does it load more rows?
- **Verdict:** "Data Integrity Risk. Infinite scroll prevents footer access and destroys spatial memory."

---

## Class 2: Dark Patterns & "Conversion Optimization"

*Deliberate hostility designed to trick the user or prevent them from leaving.*

### 7. The Trapdoor Cancel

**The Crime:** The "Save" button is a massive, high-contrast primary button. The "Cancel" button is a tiny, grey text link (10-12px), hidden in a corner.

**The Philosophy:** Usability is about helping the user make the *correct* decision, not just the *business* decision.

**Haltija Signature:**
- Identify the Form Actions container
- Compare Primary vs. Secondary action
- **Heuristic:** If Secondary Action is:
  - \`<a>\` instead of \`<button>\`, OR
  - font-size < 80% of Primary, OR
  - contrast ratio < 3:1
  → **Crime**

---

### 8. The Roach Motel

**The Crime:** Signup takes 1 click. Cancellation requires a phone call, chat with a bot, or >3 levels of menu navigation.

**Haltija Signature:**
- Navigate to "Settings"
- Search DOM for "Cancel," "Delete," "Close Account"
- If count is 0 or link is deep in nested divs → **Crime**

---

### 9. Confirmshaming

**The Crime:** "No, I prefer to pay full price" or "No, I don't like saving money."

**Haltija Signature:**
- Analyze negative action text sentiment
- Detect manipulative phrasing (keywords: "dumb," "lose," "prefer to pay," "miss out")

---

### 10. The Phantom Shield (Cookie Wall)

**The Crime:** Transparent or invisible layers (cookie banners) blocking clicks on the main UI, making the site feel broken/frozen.

**Haltija Signature:**
1. **Click Intercept Test:**
   - Fire \`click\` at center of viewport (e.g., Login button)
   - Check which element actually received the event
   - If target is \`div.cookie-wrapper\` instead of intended button → **Critical Crime**

2. **Invisible Wall Heuristic:**
   - Find elements with \`position: fixed\` covering >80% of viewport
   - Check: \`background-color: transparent\` AND \`pointer-events: auto\`?
   - Report: "Invisible High-Z Element blocking interactions. Site appears frozen."

**Severity:** Critical (Site Unusable)

---

## Class 3: Internationalization (i18n) Hostility

*Design that assumes every user is in the US, speaks English, and has a US keyboard.*

### 11. The Buried Country

**The Crime:** "United States" is at the top. "Afghanistan" is second. "Finland" is item #64. No search/typeahead.

**Haltija Signature:**
- Open dropdown
- Check index of current user's locale country
- If index > 10 and list is > 50 → **Crime**
- Test typeahead: focus list, send keystrokes "F", "I"
  - *Pass:* Selection jumps to "Fiji" then "Finland"
  - *Fail:* Nothing happens, or jumps to "France" (ignoring "I")

---

### 12. Zip Code Jail

**The Crime:** Rejecting alphanumeric postal codes (UK: \`EC1A 1BB\`, Canada: \`M5V 2H1\`) because the regex expects 5 digits.

**Haltija Signature:**
- Input \`EC1A 1BB\` into postal field
- Check for validation error
- If error → **Crime: "Globalization Fail"**

---

### 13. The Phone Number Pedant

**The Crime:** "Invalid format. Do not use dashes." / "Invalid format. You must use dashes."

**The Fix:** Strip non-digits on the backend! Don't make the user do data entry work.

**Haltija Signature:**
- Fuzz input with:
  - \`+358 40 1234567\` (Standard International)
  - \`040-123-4567\` (Local formatted)
  - \`0401234567\` (Raw)
- If *any* valid format triggers error → **Crime**

---

### 14. The Polygloat Menu

**The Crime:** Listing languages in English ("German", "Japanese") instead of endonyms ("Deutsch", "日本語").

**The Problem:** Non-English speakers can't read English! They're looking for their language *in their language*.

**Haltija Signature:**
- Scan language menu
- Regex check: Does "Spanish" match \`Español\`? "German" match \`Deutsch\`?
- If text is purely ASCII English names for non-English languages → **Crime**

---

### 15. The Cookie Wall (EU Blocker)

**The Crime:** Cookie modal so poorly implemented it's impossible to click "Login" because an invisible \`div\` covers the screen, or the "Reject" button is off-canvas on mobile.

**Haltija Signature:**
- Element: Fixed position \`div\` with high \`z-index\`, keywords "Cookie", "Consent"
- Attempt to click primary action *before* interacting with banner
- Check if click intercepted
- **GDPR Check:** Is there a \`button\` with text "Reject" or "Necessary Only"?

---

## Class 4: Forms from Hell

*Friction points that destroy data entry speed.*

### 16. The Paste Blockade

**The Crime:** Blocking \`paste\` on password or account number fields.

**Haltija Signature:**
- Attempt \`paste\` event
- Check \`defaultPrevented\`
- If blocked → **Crime**

---

### 17. The Amnesiac Form

**The Crime:** Submitting the form with one error wipes all other valid fields.

**Haltija Signature:**
- Fill form completely
- Intentionally break one field
- Submit
- Check if other fields retained values
- If wiped → **Crime**

---

### 18. The Label Lie

**The Crime:** Using \`placeholder\` text as the only label. It vanishes when you type, forcing reliance on memory.

**Haltija Signature:**
- Check input for \`<label>\` element, \`aria-label\`, or \`aria-labelledby\`
- If all missing → **Crime**

---

## Class 5: Accessibility & Mobile Hostility

*Basic exclusions of users with disabilities or touch interfaces.*

### 19. The "Div" Button

**The Crime:** \`<div>\` or \`<span>\` with \`onClick\` but no \`role="button"\` and no \`tabindex\`. Invisible to screen readers and keyboard users.

**Haltija Signature:**
- Query elements with click listeners
- Check tag name
- If generic container without proper ARIA → **Crime**

---

### 20. The Tiny Tap

**The Crime:** Interactive elements smaller than 44x44px.

**Haltija Signature:**
- Compute \`boundingClientRect\` of all \`<a>\` and \`<button>\` elements
- Flag any < 44px in either dimension

---

### 21. Focus Trap / Ghost Focus

**The Crime:** 
- Opening a modal does not trap focus inside it, OR
- Closing modal resets focus to \`<body>\` instead of the trigger button

**Haltija Signature:**
- Open modal
- Press \`Tab\` repeatedly
- If focus leaves modal → **Crime**
- Close modal
- Check \`document.activeElement\`
- If not the original trigger → **Crime**

---

## Class 6: Volatility (The "Feed" Crimes)

*Violating object permanence and user intent.*

### 22. Feed Roulette

**The Crime:** Accidental refresh or "back" button wipes the content you were looking at, replacing it with a new algorithmic feed.

**The Philosophy:** Prioritizes "Freshness" (Engagement) over "Utility" (Retrieval). Treats user attention as disposable.

**Haltija Signature:**
1. \`scanVisibleContent()\` → Store IDs of first 5 items
2. Trigger \`reload\` or click "Home"
3. \`scanVisibleContent()\` again
4. If < 50% of original items present → **Crime: "Volatile Content Environment"**

---

### 23. The Gaslighting Scroll (Bi-Directional Virtualization)

**The Crime:** You're 500 items deep. You scroll up to check something you saw 30 seconds ago. The browser jumps, content re-orders, you can't find your place.

**The Philosophy:** Humans rely on spatial memory ("It was up and to the left"). Virtual scrolling breaks this map.

**Haltija Signature:**
1. Scroll down 50 viewport heights
2. Scroll up 10 viewport heights quickly
3. Monitor \`scroll\` events vs \`visualViewport\` offset
4. If scroll position jumps (>100px without user input) → **Crime**
5. If \`layout-shift\` score spikes during scroll-up → **Crime**

---

### 24. Deceptive Loading (Skeleton Lie)

**The Crime:** Skeleton screen shows a layout, but final content shifts positions significantly (CLS) or buttons remain disabled after appearing ready.

**The Philosophy:** The UI promises interaction ("I am loading right here") but delivers a moving target.

**Haltija Signature:**
- Compare \`boundingClientRect\` of skeleton elements vs. final content
- If shift > 10px → **Crime: "Deceptive Loading State"**

---

## Implementation: The "Rap Sheet"

When Haltija runs a test plan, output a **Criminal Record** alongside functional results:

\`\`\`
Summary:
- Functional: PASSED (Login works)
- UX Audit: FAILED

Crimes Detected:
1. FELONY: Paste Blockade on Password Field
2. MISDEMEANOR: Tiny Tap Target on "Forgot Password" link (12px height)
3. INTERACTION VIOLATION: Country picker lacks typeahead
4. DARK PATTERN: Cancel button is 10px grey text link
\`\`\`

This gives engineers/designers **exact ammunition** for the next meeting.

---

## Why Agents Hate These Even More Than Humans

To an AI Agent, **The Feed is Kryptonite.**

- Agents act linearly: "I saw a shoe I liked. I will scroll back up to buy it."
- If scrolling up makes the shoe vanish (Virtual Scroll) or reloading changes inventory (Feed Roulette), the Agent fails.

**The Haltija Advantage:**
Because Haltija acts as a **Context History Stream** (Semantic Events), it solves this:

- **The Site:** Deletes DOM node for "Post #101" because you scrolled past it
- **Haltija:** Remembers "Post #101" was seen at \`timestamp: 10:05\`
- **The Feature:** When Agent asks "Where is that post?", Haltija says: *"The site deleted it (Virtual Scroll), but I have the data. Don't scroll up; use Search instead."*

You are building **the memory that the modern web tries to erase**.

---

## Class 7: Mobile Hostility

*Crimes committed by developers who only test on a 27-inch monitor with a mouse.*

### 25. The Pinch-to-Zoom Lock

**The Crime:** Disabling zoom because it "messes up the design." This actively prevents users with vision impairments (or anyone in bright sunlight) from reading your content.

**Haltija Signature:**
- Scan \`<meta name="viewport">\`
- Look for \`user-scalable=no\` or \`maximum-scale=1.0\`

**Report:** "Viewport Violation: Zoom disabled. Accessibility failure for low-vision users."

---

### 26. The Hover Trap

**The Crime:** Hiding critical actions (like "Edit" or "Delete" buttons) or navigation sub-menus behind a \`:hover\` state.

**The Reality:** There is no hover on touchscreens. The user has to awkwardly tap once to see the menu (which might interpret the tap as a click and navigate away immediately).

**Haltija Signature:**
- Identify elements with \`mouseover\` or \`:hover\` listeners that change visibility of child elements
- **Heuristic:** Can the Agent access the child element via a single \`click\` or \`focus\` event without triggering navigation?

**Report:** "Touchscreen Exclusion: Critical UI hidden behind Hover state. Inaccessible on mobile."

---

### 27. The Keyboard Eclipse

**The Crime:** Tapping an input field brings up the on-screen keyboard, which completely covers the input field you are typing in.

**Haltija Signature:**
- **Simulation:** Set viewport height to 50% (simulating keyboard)
- **Action:** Focus an input in the bottom half of the page
- **Check:** Is the input element's \`bottom\` coordinate > visible viewport height? Does the page fail to scroll it into view?

**Report:** "Input Occlusion: Active field hidden by virtual keyboard."

---

### 28. The Fat Finger Minefield

**The Crime:** Placing two actionable elements (e.g., "Save" and "Cancel", or list items) closer than 8px apart.

**Haltija Signature:**
- Scan all \`button\`, \`a\`, \`input\`
- Compute bounding boxes
- **Check:** If distance between edges of two interactive targets is < 8px → **Crime**

**Report:** "Touch Target Risk: Interactive elements too close. High probability of accidental clicks."

---

### 29. The Horizontal Scroll of Death

**The Crime:** A single element (like a long URL or code block) is wider than the mobile viewport, causing the *entire page* to wobble left and right.

**Haltija Signature:**
- Set viewport width to 375px (iPhone SE)
- **Check:** Is \`document.body.scrollWidth\` > \`window.innerWidth\`?

**Report:** "Layout Failure: Page overflows horizontally. Causes unstable scrolling."

---

## Class 8: Accessibility Atrocities

*Basic exclusions that are often illegal and always unethical.*

### 30. The Silent Image

**The Crime:** Meaningful images (not decorative) missing \`alt\` text. Screen readers just say "Image" or read the filename "DSC_0043.jpg".

**Haltija Signature:**
- Query \`img:not([alt])\`
- Filter out \`role="presentation"\` or empty \`alt=""\` (if decorative)

**Report:** "Blind Spot: Meaningful image missing alternative text."

---

### 31. The Color-Only Signal

**The Crime:** Using *only* red text or a red border to indicate an error, with no icon or text label explaining "Invalid".

**The Reality:** Colorblind users cannot see the error.

**Haltija Signature:**
- Trigger form error
- **Check:** Did a new text node appear or did \`aria-invalid\` toggle?
- **Failure:** If only CSS \`color\` or \`border-color\` changed → **Crime**

**Report:** "Sensory Reliance: Error state conveyed solely by color. Invisible to colorblind users."

---

### 32. The Low Contrast Grey

**The Crime:** Light grey text on a white background (e.g., \`#999\` on \`#fff\`). The designer thinks it looks "clean." Users think it looks "invisible."

**Haltija Signature:**
- **Heuristic:** Compute background color and foreground color of all text nodes
- **Math:** Calculate luminosity ratio
- If < 4.5:1 (WCAG AA) for normal text → **Crime**

**Report:** "Legibility Failure: Text contrast too low (Ratio X:1)."

---

### 33. The Headings Out of Order

**The Crime:** Using \`<h3>\` because you wanted "medium sized font," skipping \`<h1>\` or \`<h2>\`.

**The Reality:** Screen reader users navigate by headings. A broken hierarchy makes the page structure unintelligible.

**Haltija Signature:**
- Scan heading tags
- Check order (e.g., \`h4\` appears before \`h1\`, or \`h3\` is a direct child of \`h1\` skipping \`h2\`)

**Report:** "Structural Chaos: Semantic heading hierarchy broken."

---

### 34. The Autoplay Assault

**The Crime:** Video or audio that plays automatically on page load.

**The Reality:** This overrides screen reader audio, disorienting blind users, and triggers anxiety/migraines in neurodiverse users.

**Haltija Signature:**
- Check \`<video>\` or \`<audio>\` tags for \`autoplay\` attribute
- Check if \`muted\` is missing

**Report:** "Hostile Media: Unsolicited autoplay detected."

---

### 35. The No Skip Link

**The Crime:** Forcing keyboard users to tab through 50 navigation links on *every single page* before they can reach the content.

**Haltija Signature:**
- **Action:** Press \`Tab\` from page load
- **Check:** Is one of the first 3 focusable elements a link to \`#main\` or \`main\`?

**Report:** "Navigation Fatigue: Missing 'Skip to Content' link."

---

## Implementation Strategy: The Audit Flag

You don't want this running on every fast iteration loop (it generates too much noise).

**Add a flag to the Haltija CLI:**

\`\`\`bash
# Run functional tests only
npx haltija test

# Run with full Criminal Investigation
npx haltija test --audit
\`\`\`

When \`--audit\` is active, the Agent gets the "Criminal Code" system prompt and the Haltija widget activates its "Sensors" (Contrast checker, Layout shift observer, etc.).

This allows teams to separate:
- **"Did we break the build?"** (Functional)
- **"Did we ruin the product?"** (Audit)

---

## The Value Proposition

You aren't just selling a "Tester." You are selling a **Compliance Officer**.

If a company uses Haltija, they aren't just checking if the login button works. They're checking:

- "Did we alienate our European customers today?"
- "Did we break the site for Canada?"
- "Is our mobile menu usable by humans?"

This turns **JSON Test Results** into a **Business Risk Report**. That's worth 10x what a Selenium script is worth.

---

## Severity Levels

| Level | Description | Example |
|-------|-------------|---------|
| **Critical** | Site unusable | Phantom Shield blocking all clicks |
| **Felony** | Major user harm | Paste Blockade on passwords |
| **Misdemeanor** | Friction/annoyance | Tiny tap targets |
| **Violation** | Best practice breach | Missing form labels |
| **Warning** | Potential issue | Country picker lacks typeahead |

---

## Future Additions (Parking Lot)

From original roadmap, not yet codified:

- **CAPTCHA nightmares** - inaccessible, unsolvable
- **Hamburger menus hiding critical actions** - primary nav buried
- **No skip links** - keyboard users trapped in header
- **Hover-dependent UI on mobile** - tooltips/menus that require hover
- **Pinch-zoom disabled** - viewport meta crimes
- **Auto-formatting that fights input** - phone fields that add/remove chars while typing
- **Duplicate country entries** - "UK" vs "Great Britain" vs "United Kingdom"
- **Language selector buried** - in footer? hamburger? settings? random flag icon?
- **Missing lang attribute** - wrong language auto-detected, no way to fix
`
