/**
 * The legal `action` values for a test-suite step — ONE definition, carrying its own prose.
 *
 * There was no such list. `hj api` documents the HTTP endpoints, which reads as though the same
 * verbs work as steps, and `/drag` is documented there — so a suite using `{"action": "drag"}` was a
 * perfectly reasonable thing to write, validated clean, and then failed in CI with "Unsupported step
 * action: drag" (issue #30). The capability existed; only the runner's switch didn't know.
 *
 * **The description lives HERE, beside the definition, and the docs are generated from it.** Adding
 * a step type means writing its one-line summary and example in the same edit that adds it — you
 * cannot forget the documentation, because it is the thing you are looking at. The alternative,
 * which this replaces, was three hand-maintained copies of the list (SKILL.md, CLAUDE.md,
 * docs/CI-INTEGRATION.md) that nothing checked and that silently drifted. Keeping documentation in
 * step with code has been this project's most persistent failure, and every durable fix has had the
 * same shape: make the second copy a build artifact rather than a promise.
 *
 * Three things are enforced against this list:
 *   - `src/test-actions.test.ts` — the runner's `switch (step.action)` contains exactly these
 *   - `/test/validate` — rejects an unknown action before a suite runs
 *   - `bun run build` — regenerates the doc blocks; `docs-drift.yml` fails if they are stale
 */

export interface TestActionDoc {
  /**
   * Is this action CORE — worth spending main-prompt budget on?
   *
   * The agent-facing prompt is loaded on every invocation, so every line in it competes with the
   * user's actual task for attention and context. Marking this is mandatory (no default) because a
   * default would always be taken, and everything would drift into "core" one reasonable addition
   * at a time. Non-core actions are still fully documented — in the generated reference, which is
   * read on demand rather than always.
   *
   * The bar: would a competent agent driving a browser for the first time be unable to do the job
   * without it? Recorder-generated steps (select/cut/copy/paste) and specialised ones (drag, verify,
   * tabs-*) are looked up when needed; navigate/click/type/wait/assert/eval are not.
   */
  core: boolean
  /** One line: what the step does. Rendered into every generated table. */
  summary: string
  /** A minimal, valid example — the thing a reader copies. */
  example: string
  /** Named fields beyond `action`, most important first. */
  fields?: string
}

/**
 * Every legal step action, in the order they are presented to a reader.
 *
 * A `Record` rather than an array of strings so a new action cannot be added without its prose:
 * the type makes `summary` and `example` mandatory.
 */
export const TEST_ACTIONS = {
  navigate: {
    core: true,
    summary: 'Load a URL, then wait for the widget to reconnect in that same tab.',
    fields: '`url`',
    example: '{"action": "navigate", "url": "http://localhost:3000/login"}',
  },
  click: {
    core: true,
    summary:
      'Realistic click (scroll into view, mouseenter/over/down/up/click). Prefers the match a user could act on when several exist.',
    fields: '`selector` or `ref`',
    example: '{"action": "click", "selector": "button:text(Sign in)"}',
  },
  type: {
    core: true,
    summary:
      'Per-character typing with the full key lifecycle. `paste: true` for fast entry that still triggers framework validation.',
    fields: '`selector`/`ref`, `text`, `clear`, `paste`, `humanlike`',
    example: '{"action": "type", "selector": "#email", "text": "a@b.com"}',
  },
  check: {
    core: false,
    summary: 'Toggle a checkbox or radio via a realistic click.',
    fields: '`selector` or `ref`',
    example: '{"action": "check", "selector": "#agree"}',
  },
  key: {
    core: true,
    summary: 'Press a key, optionally with modifiers, at the focused element.',
    fields: '`key`, `selector`, `modifiers`',
    example: '{"action": "key", "key": "Enter"}',
  },
  'select-text': {
    core: false,
    summary: 'Select TEXT within an element (generated by the recorder) — not choosing a dropdown option.',
    fields: '`selector`, `text`',
    example: '{"action": "select-text", "selector": "#note"}',
  },
  cut: {
    core: false,
    summary: 'Dispatch a cut event at the element (generated by the recorder).',
    fields: '`selector`, `text`',
    example: '{"action": "cut", "selector": "#note"}',
  },
  copy: {
    core: false,
    summary: 'Dispatch a copy event at the element (generated by the recorder).',
    fields: '`selector`, `text`',
    example: '{"action": "copy", "selector": "#note"}',
  },
  paste: {
    core: false,
    summary: 'Dispatch a paste event at the element (generated by the recorder).',
    fields: '`selector`, `text`',
    example: '{"action": "paste", "selector": "#note"}',
  },
  drag: {
    core: false,
    summary:
      "Drag from the element's centre by a pixel delta — sliders, resize handles, drag-reorder lists.",
    fields: '`selector`/`ref`, `deltaX`, `deltaY`, `duration`',
    example: '{"action": "drag", "selector": ".slider-thumb", "deltaX": 50}',
  },
  wait: {
    core: true,
    summary:
      'Pause, or poll until something is true. **Must be given something to wait for** — a wait with none of these fields is an error, not a no-op.',
    fields: '`duration` (ms), `selector` (alias `forElement`), `forWindow`, `url`',
    example: '{"action": "wait", "selector": ".dashboard", "timeout": 10000}',
  },
  assert: {
    core: true,
    summary: 'Fail the step unless the assertion holds.',
    fields: '`assertion` — `exists`, `visible`, `hidden`, `text`, `value`, `attribute`, `url`',
    example: '{"action": "assert", "assertion": {"type": "visible", "selector": ".dashboard"}}',
  },
  eval: {
    core: true,
    summary:
      'Run JavaScript in the page. Async works; multi-statement code needs an explicit `return`.',
    fields: '`code`',
    example: '{"action": "eval", "code": "return document.title"}',
  },
  verify: {
    core: false,
    summary: 'Poll an expression until it matches an expectation (or time out).',
    fields: '`eval`, `expect`',
    example: '{"action": "verify", "eval": "app.items.length", "expect": {"equals": 3}}',
  },
  'tabs-open': {
    core: false,
    summary: 'Open a new tab (desktop app). Follow with `wait` + `forWindow` to await its widget.',
    fields: '`url`',
    example: '{"action": "tabs-open", "url": "http://localhost:3000"}',
  },
  'tabs-close': {
    core: false,
    summary: 'Close a tab by window id.',
    fields: '`window`',
    example: '{"action": "tabs-close", "window": "hj-abc-1"}',
  },
  'tabs-focus': {
    core: false,
    summary:
      'Point untargeted commands at a tab — a server-side routing change, so it cannot time out on a hidden tab.',
    fields: '`window`',
    example: '{"action": "tabs-focus", "window": "hj-abc-1"}',
  },
} as const satisfies Record<string, TestActionDoc>

/**
 * Old spellings that still work, mapped to what they are now called.
 *
 * `select` was renamed because it did not mean what every reader thinks it means. Measured, not
 * guessed: shown the bare vocabulary, 3/3 agents reached for `select` to choose a dropdown option,
 * and 3/3 read it cold as "choose an <option>". NOBODY read it as text selection, which is what it
 * does. A name that unanimously means something else is not a documentation problem.
 *
 * Kept as an alias so existing suites keep running. **When it is eventually dropped, `select` is
 * free to mean the thing everyone already expects — pick an option — which haltija cannot do at
 * all today.** The two meanings must never overlap: a word that means both text-selection and
 * option-picking, depending on vintage, is precisely the silent-wrong-action trap this rename
 * exists to remove. So `assertNoAliasShadowsAction` below is a hard invariant, not a style rule.
 */
export const DEPRECATED_ACTION_ALIASES: Record<string, string> = {
  select: 'select-text',
}

export const TEST_STEP_ACTIONS = Object.keys(TEST_ACTIONS) as Array<keyof typeof TEST_ACTIONS>

/** One accessor, so `TEST_ACTIONS[a] as TestActionDoc` stops appearing six times. */
function docFor(action: TestStepAction): TestActionDoc {
  return TEST_ACTIONS[action]
}

/**
 * The actions in a tier.
 *
 * The `filter(a => TEST_ACTIONS[a].core)` expression appeared four times, each with its own cast.
 * A cast repeated is a cast nobody rechecks — and these ones would have hidden a real type error if
 * an entry ever lost a field, which the `satisfies` clause is there to catch.
 */
function actionsInTier(coreOnly: boolean): TestStepAction[] {
  return coreOnly ? TEST_STEP_ACTIONS.filter((a) => docFor(a).core) : TEST_STEP_ACTIONS
}

/**
 * Canonical action for whatever the author wrote, plus the old name if one was used.
 *
 * Everything that dispatches or validates a step goes through this, so an alias cannot work in one
 * place and fail in another — which is the drift this whole release cycle has been about.
 */
export function resolveStepAction(action: unknown): { action: string; deprecatedFrom?: string } {
  if (typeof action !== 'string') return { action: String(action) }
  const canonical = DEPRECATED_ACTION_ALIASES[action]
  return canonical ? { action: canonical, deprecatedFrom: action } : { action }
}

/** The message shown when a suite uses an old spelling. Names the replacement, never just complains. */
export function deprecationNotice(from: string, to: string): string {
  return `\`${from}\` is deprecated — use \`${to}\`. It still runs, but the old name will be removed, and \`${from}\` is being freed for a different meaning.`
}

export type TestStepAction = keyof typeof TEST_ACTIONS

const ACTION_SET: ReadonlySet<string> = new Set(TEST_STEP_ACTIONS as readonly string[])

/**
 * A CANONICAL action — one that `TEST_ACTIONS` actually has an entry for.
 *
 * The narrowing has to be honest: the previous version also returned true for aliases while
 * claiming `action is TestStepAction`, so `TEST_ACTIONS[a]` type-checked and was `undefined` at
 * runtime. Verified — `isTestStepAction('select')` was true and `TEST_ACTIONS['select']` was
 * undefined. Today's only caller resolves the alias first, so nothing was broken; a type that lies
 * is a trap set for the next caller.
 */
export function isTestStepAction(action: unknown): action is TestStepAction {
  return typeof action === 'string' && ACTION_SET.has(action)
}

/**
 * Legal to WRITE in a suite — canonical or a deprecated alias.
 *
 * This is what validation wants: a file written before a rename must not start failing. It does not
 * narrow to `TestStepAction`, because an alias has no entry to look up.
 */
export function isKnownStepAction(action: unknown): boolean {
  return (
    typeof action === 'string' && (ACTION_SET.has(action) || action in DEPRECATED_ACTION_ALIASES)
  )
}

/**
 * The generated markdown table, written into the docs by `bun run build`.
 *
 * `coreOnly` is what keeps the main prompt from growing without limit: the agent-facing skill gets
 * the core rows plus a pointer, the reference gets everything.
 */
export function stepActionsTable(opts: { coreOnly?: boolean } = {}): string {
  const rows = actionsInTier(!!opts.coreOnly).map((a) => {
    const d = docFor(a)
    // The example is rendered HERE and only here: it is mandatory on every entry, and a mandatory
    // field with no consumer is a field that rots. It stays out of the compact prompt line, which
    // is budget-constrained — the reference is where an example earns its bytes.
    return `| \`${a}\` | ${d.fields ?? '—'} | ${d.summary} | \`${d.example}\` |`
  })
  return [
    '| action | fields | what it does | example |',
    '| --- | --- | --- | --- |',
    ...rows,
  ].join('\n')
}

/** The generated compact list, for places where a table is too heavy. */
export function stepActionsInline(opts: { coreOnly?: boolean } = {}): string {
  return actionsInTier(!!opts.coreOnly).map((a) => `\`${a}\``).join(', ')
}

/**
 * The COMPACT rendering for the main prompt: one line, fields only.
 *
 * A three-column table with a sentence per row costs ~1.2KB; this costs ~200 bytes and carries the
 * part an agent cannot guess — the field names. What `click` does is inferable from its name; that
 * `wait` needs a target, and which fields satisfy it, is not. Budget spent where it buys something.
 */
export function stepActionsCompact(): string {
  return actionsInTier(true)
    .map((a) => {
      const d = docFor(a)
      const fields = (d.fields ?? '').replace(/`/g, '').replace(/ \(ms\)| \(alias [^)]+\)/g, '')
      return `\`${a}\`${fields ? ` — ${fields}` : ''}`
    })
    .join('; ')
}

/** Actions deliberately kept OUT of the main prompt — named so the reference can point at them. */
export function nonCoreActionsInline(): string {
  return TEST_STEP_ACTIONS.filter((a) => !docFor(a).core)
    .map((a) => `\`${a}\``)
    .join(', ')
}

/**
 * Static problems with one step — things knowable without a browser.
 *
 * Deliberately NOT a full schema check. It covers the two failures that reach CI looking like a
 * pass: an action the runner cannot dispatch, and a `wait` with nothing to wait for (which used to
 * be reported as a PASSING step, so a guard that had never waited for anything looked green).
 */
export function staticStepIssue(step: Record<string, unknown>): string | null {
  const action = resolveStepAction(step.action).action
  // `action` is already alias-resolved above, so the CANONICAL check is the right one here.
  if (!isTestStepAction(action)) {
    const near = typeof action === 'string' ? nearest(action) : null
    return (
      `unknown step action ${JSON.stringify(action)}` +
      (near ? ` — did you mean "${near}"?` : '') +
      `. Legal actions: ${TEST_STEP_ACTIONS.join(', ')}. ` +
      `Note that an HTTP endpoint existing (see \`hj api\`) does not by itself make it a step.`
    )
  }
  if (action === 'assert') {
    // The runner reads `step.assertion`; a FLAT `{action:'assert', type:'exists', selector:…}` has
    // none, so the assertion never runs. Our own CLAUDE.md documented the flat shape, which is how
    // plausible it looks — and an assertion that does not run is a guard that cannot fail, the same
    // shape as the `wait` case below.
    const assertion = step.assertion as { type?: unknown } | undefined
    if (!assertion || typeof assertion !== 'object') {
      const stray = ['type', 'selector', 'value', 'pattern'].filter((k) => step[k] !== undefined)
      return (
        'assert step has no `assertion` object' +
        (stray.length ? ` — found ${stray.map((k) => `\`${k}\``).join(', ')} at the top level, which the runner ignores` : '') +
        '. Use `{"action":"assert","assertion":{"type":"exists","selector":"…"}}`.'
      )
    }
    if (!assertion.type) {
      return 'assert step has an `assertion` with no `type` — nothing will be checked.'
    }
  }
  if (action === 'wait') {
    const hasTarget =
      step.duration != null ||
      (step as { ms?: unknown }).ms != null ||
      step.selector != null ||
      step.forElement != null ||
      step.forWindow != null ||
      step.url != null
    if (!hasTarget) {
      return (
        'wait step has nothing to wait for — give it `duration` (ms), `selector` (or ' +
        '`forElement`), `forWindow: true`, or `url`. A wait that waits for nothing reports success ' +
        'and lets every later step race the page.'
      )
    }
  }
  return null
}

/** Closest legal action by edit distance, for a "did you mean" — only when it is genuinely close. */
function nearest(input: string): string | null {
  let best: string | null = null
  let bestScore = Infinity
  for (const a of TEST_STEP_ACTIONS) {
    const d = editDistance(input.toLowerCase(), a)
    if (d < bestScore) {
      bestScore = d
      best = a
    }
  }
  return bestScore <= 3 ? best : null
}

function editDistance(a: string, b: string): number {
  const m = a.length
  const n = b.length
  let prev = Array.from({ length: n + 1 }, (_, j) => j)
  for (let i = 1; i <= m; i++) {
    const cur = [i]
    for (let j = 1; j <= n; j++) {
      cur[j] = Math.min(prev[j] + 1, cur[j - 1] + 1, prev[j - 1] + (a[i - 1] === b[j - 1] ? 0 : 1))
    }
    prev = cur
  }
  return prev[n]
}
