/**
 * Haltija - Browser Control for AI Agents
 * https://github.com/tonioloewald/haltija
 *
 * Copyright 2025 Tonio Loewald
 * SPDX-License-Identifier: Apache-2.0
 *
 * ⚠️  AUTO-GENERATED FROM package.json - DO NOT EDIT THIS FILE
 * ⚠️  To change the version, update package.json and run: bun run build
 */

export const VERSION = '1.1.8'
